routes/web.php
            Route::get('uploads/all/{collection?}', 'UploadController@all');
            Route::get('uploads/collectionsNames', 'UploadController@collectionsNames');
            Route::post('uploads/clear', 'UploadController@clear')->name('medias.delete');
            Route::get('medias', 'UploadController@index')->name('medias');
            Route::get('uploads/clear-all', 'UploadController@clearAll');
        });

        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::get('permissions/role-has-permission', 'PermissionController@roleHasPermission');
            Route::get('permissions/refresh-permissions', 'PermissionController@refreshPermissions');
        });
        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::post('permissions/give-permission-to-role', 'PermissionController@givePermissionToRole');
            Route::post('permissions/revoke-permission-to-role', 'PermissionController@revokePermissionToRole');
        });

        Route::group(['middleware' => ['permission:app-settings']], function () {
            Route::prefix('settings')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::resource('roles', 'RoleController');
                Route::resource('customFields', 'CustomFieldController');
                Route::resource('currencies', 'CurrencyController')->except([
                    'show'
                ]);
                Route::get('users/login-as-user/{id}', 'UserController@loginAsUser')->name('users.login-as-user');
                Route::patch('update', 'AppSettingController@update');
                Route::patch('translate', 'AppSettingController@translate');
                Route::get('sync-translation', 'AppSettingController@syncTranslation');
                Route::get('clear-cache', 'AppSettingController@clearCache');
                Route::get('check-update', 'AppSettingController@checkForUpdates');
                // disable special character and number in route params
                Route::get('/{type?}/{tab?}', 'AppSettingController@index')
                    ->where('type', '[A-Za-z]*')->where('tab', '[A-Za-z]*')->name('app-settings');
            });
        });

        Route::post('fields/remove-media', 'FieldController@removeMedia');
        Route::resource('fields', 'FieldController')->except([
            'show'
        ]);

        Route::post('markets/remove-media', 'MarketController@removeMedia');
        Route::resource('markets', 'MarketController')->except([
            'show'
        ]);
        Route::get('markets/{id}/settings', 'MarketController@settings')->name('markets.settings');
        Route::post('markets/{id}/settings/weight_based_gtin', 'MarketController@weightBasedGtinPost')->name('markets.settings.weight_based_gtin.post');

        Route::resource('customers', 'CustomerController');

        Route::post('categories/remove-media', 'CategoryController@removeMedia');
        Route::resource('categories', 'CategoryController')->except([
            'show'
        ]);

        Route::resource('faqCategories', 'FaqCategoryController')->except([
            'show'
        ]);

        Route::resource('orderStatuses', 'OrderStatusController');

        Route::get('products/update_amounts', 'ProductController@updateAmounts');
        Route::post('products/update_amounts', 'ProductController@postUpdateAmounts');
        Route::get('products/import_from_database/{market_id}', 'ProductController@importFromDatabase')->name('products.import_from_database');
        Route::get('products/reload_from_server/{product_id}', 'ProductController@reloadFromServer')->name('products.reload_from_server');
        Route::post('products/import_from_database/{market_id}', 'ProductController@postImportFromDatabase')->name('products.import_from_database.post');
        Route::post('products/remove-media', 'ProductController@removeMedia');
        Route::resource('products', 'ProductController')->except([
            'show'
        ]);

        Route::post('galleries/remove-media', 'GalleryController@removeMedia');
        Route::resource('galleries', 'GalleryController')->except([
            'show'
        ]);

        Route::resource('productReviews', 'ProductReviewController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');


        Route::resource('payments', 'PaymentController')->except([
            'create',
            'store',
            'edit',
            'destroy'
        ]);
        ;

        Route::resource('faqs', 'FaqController')->except([
            'show'
        ]);
        Route::resource('marketReviews', 'MarketReviewController')->except([
            'show'
        ]);

        Route::resource('favorites', 'FavoriteController')->except([
            'show'
        ]);

        Route::get('orders/list/{type}', 'OrderController@list')->name('orders.list');
        Route::post('orders/{order_id}/add_product', 'OrderController@addProductOrder')->name('orders.add_product');
        Route::post('orders/{order_id}/remove_product/{product_id}', 'OrderController@removeProductOrder')->name('orders.remove_product');
        Route::post('orders/mark_as_sent', 'OrderController@markAsSent')->name('orders.mark_as_sent');
        Route::post('orders/mark_as_delivered', 'OrderController@markAsDelivered')->name('orders.mark_as_delivered');
        Route::get('orders/{order_id}/mark_as_delivered', 'OrderController@deliverOrder')->name('orders.deliver');
        Route::get('orders/{order_id}/mark_as_paid', 'OrderController@markAsPaid')->name('orders.mark_as_paid');
        Route::get('orders/{order_id}/change_status/{status}', 'OrderController@changeStatus')->name('orders.change_status');
        Route::get('orders/{order_id}/print_payment_receipt', 'OrderController@printPaymentReceipt')->name('orders.print_payment_receipt');
        Route::put('orders/{order_id}/restore', 'OrderController@restore')->name('orders.restore');
        Route::put('orders/{order_id}/update_quantities', 'OrderController@updateQuantities')->name('orders.update_quantities');
        Route::post('orders/{order_id}/add_new_product', 'OrderController@addProductOrder')->name('orders.add_new_product');
        Route::resource('orders', 'OrderController');

        Route::resource('notifications', 'NotificationController')->except([
            'create',
            'store',
            'update',
            'edit',
        ]);
        ;

        Route::resource('carts', 'CartController')->except([
            'show',
            'store',
            'create'
        ]);
        Route::resource('deliveryAddresses', 'DeliveryAddressController')->except([
            'show'
        ]);

        Route::get('drivers/reports', 'DriverController@reports')->name('drivers.reports');
        Route::post('drivers/remove-media', 'DriverController@removeMedia');
        Route::resource('drivers', 'DriverController');

        Route::get('order_pickers/reports', 'OrderPickerController@reports')->name('order_pickers.reports');
        Route::post('order_pickers/remove-media', 'OrderPickerController@removeMedia');
        Route::resource('order_pickers', 'OrderPickerController');

        Route::resource('earnings', 'EarningController')->except([
            'show',
            'edit',
            'update'
        ]);

        Route::resource('driversPayouts', 'DriversPayoutController')->except([
            'show',
            'edit',
            'update'
        ]);

        Route::resource('marketsPayouts', 'MarketsPayoutController')->except([
            'show',
            'edit',
            'update'
        ]);

        Route::resource('optionGroups', 'OptionGroupController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');

        Route::resource('options', 'OptionController')->except([
            'show'
        ]);

        Route::get('account', 'AccountController@index')->name('account.index');
        Route::get('account/add_market', 'AccountController@addMarket')->name('account.add_market');
        Route::post('account/add_market', 'AccountController@postAddMarket')->name('account.add_market.post');
        Route::get('account/monthly_payments', 'AccountController@monthlyPayments')->name('account.monthly_payments');
        Route::get('account/show_monthly_payment/{mp}', 'AccountController@showMonthlyPayment')->name('account.show_monthly_payment');
        Route::post('account/pay_monthly_payment/{mp}', 'AccountController@payMonthlyPayment')->name('account.pay_monthly_payment');



        Route::get('cash_register', 'CashRegisterController@index')->name('cash_register.index');
    });

    Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
    Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');
    Auth::routes(['password.reset' => false]);

    Route::get('payments/failed', 'PayPalController@index')->name('payments.failed');
    Route::get('payments/razorpay/checkout', 'RazorPayController@checkout');
    Route::post('payments/razorpay/pay-success/{userId}/{deliveryAddressId?}', 'RazorPayController@paySuccess');
    Route::get('payments/razorpay', 'RazorPayController@index');

    Route::get('payments/paypal/express-checkout', 'PayPalController@getExpressCheckout')->name('paypal.express-checkout');
    Route::get('payments/paypal/express-checkout-success', 'PayPalController@getExpressCheckoutSuccess');
    Route::get('payments/paypal', 'PayPalController@index')->name('paypal.index');


app/Http/Controllers/API/Driver/OrderAPIController.php
<?php

namespace App\Http\Controllers\API\Driver;

use App\Criteria\Orders\OrdersOfUserCriteria;
use App\Events\OrderPaymentConfirmed;
use App\Models\Order;
use App\Models\PartialPayments;
use App\Repositories\CartRepository;
use App\Repositories\CustomFieldRepository;
use App\Repositories\NotificationRepository;
use App\Repositories\OrderRepository;
use App\Repositories\OrderStatusRepository;
use App\Repositories\PaymentRepository;
use App\Repositories\ProductOrderRepository;
use App\Repositories\UserRepository;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Log;
use InfyOm\Generator\Criteria\LimitOffsetCriteria;
use Prettus\Repository\Criteria\RequestCriteria;
use Prettus\Repository\Exceptions\RepositoryException;

class OrderAPIController extends Controller
{
    /** @var  OrderRepository */
    private $orderRepository;
    /** @var  ProductOrderRepository */
    private $productOrderRepository;
    /** @var  CartRepository */
    private $cartRepository;
    /** @var  UserRepository */
    private $userRepository;
    /** @var  PaymentRepository */
    private $paymentRepository;
    /** @var  NotificationRepository */
    private $notificationRepository;


    public function __construct(OrderRepository $orderRepo, CustomFieldRepository $customFieldRepo, UserRepository $userRepo, OrderStatusRepository $orderStatusRepo, NotificationRepository $notificationRepo, PaymentRepository $paymentRepo)
    {
        parent::__construct();
        $this->orderRepository = $orderRepo;
        $this->customFieldRepository = $customFieldRepo;
        $this->userRepository = $userRepo;
        $this->orderStatusRepository = $orderStatusRepo;
        $this->notificationRepository = $notificationRepo;
        $this->paymentRepository = $paymentRepo;
    }
    /**
     * Display a listing of the Order.
     * GET|HEAD /orders
     *
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function index(Request $request)
    {
        $user = $this->userRepository->findByField('api_token', $request->input('api_token'))->first();
        if (!$user) {
            return $this->sendError('User not found', 401);
        }

        try {
            $this->orderRepository->pushCriteria(new RequestCriteria($request));
            $this->orderRepository->pushCriteria(new LimitOffsetCriteria($request));
        } catch (RepositoryException $e) {
            Flash::error($e->getMessage());
        }

        if($request->createdBetween){
            $start_date = explode(';', $request->createdBetween)[0];
            $final_date = explode(';', $request->createdBetween)[1];

            $this->orderRepository->whereDate('created_at', '>=', $start_date)->whereDate('created_at', '<=', $final_date);
        }

        if($request->deliveredBetween){
            $start_date = explode(';', $request->createdBetween)[0];
            $final_date = explode(';', $request->createdBetween)[1];

            $this->orderRepository->whereDate('delivery_date', '>=', $start_date)->whereDate('delivery_date', '<=', $final_date);
        }

        $orders = $this->orderRepository->where('driver_id', $user->id)->get();

        return $this->sendResponse($orders->toArray(), 'Orders retrieved successfully');
    }

    /**
     * Display the specified Order.
     * GET|HEAD /orders/{id}
     *
     * @param int $id
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function show(Request $request, $id)
    {
        $user = $this->userRepository->findByField('api_token', $request->input('api_token'))->first();
        if (!$user) {
            return $this->sendError('User not found', 401);
        }

        /** @var Order $order */
        if (!empty($this->orderRepository)) {
            try {
                $this->orderRepository->pushCriteria(new RequestCriteria($request));
                $this->orderRepository->pushCriteria(new LimitOffsetCriteria($request));
            } catch (RepositoryException $e) {
                Flash::error($e->getMessage());
            }

            $this->orderRepository->where('driver_id', $user->id);
            $order = $this->orderRepository->findWithoutFail($id);
        }

        if (empty($order)) {
            return $this->sendError('Order not found');
        }

        $return = $order->toArray();
        $return['already_paid_amount'] = PartialPayments::where('order_id', $order['id'])->sum('amount');

        return $this->sendResponse($return, 'Order retrieved successfully');


    }

    /**
     * Display the specified Order.
     * GET|HEAD /orders/{id}
     *
     * @param string $payment_hash
     *
     * @return \Illuminate\Http\JsonResponse
     */
    public function orderByPaymentHash(Request $request, $id)
    {
        $user = $this->userRepository->findByField('api_token', $request->input('api_token'))->first();
        if (!$user) {
            return $this->sendError('User not found', 401);
        }

        /** @var Order $order */
        if (!empty($this->orderRepository)) {
            try {
                $this->orderRepository->pushCriteria(new RequestCriteria($request));
                $this->orderRepository->pushCriteria(new LimitOffsetCriteria($request));
            } catch (RepositoryException $e) {
                Flash::error($e->getMessage());
            }

            $this->orderRepository->where('driver_id', $user->id);
            $order = $this->orderRepository->findWithoutFail($id);
        }

        if (empty($order)) {
            return $this->sendError('Order not found');
        }

        $return = $order->toArray();
        $return['already_paid_amount'] = PartialPayments::where('order_id', $order['id'])->sum('amount');

        return $this->sendResponse($return, 'Order retrieved successfully');
    }

    public function markAsDelivered(Request $request, $id){
        $user = $this->userRepository->findByField('api_token', $request->input('api_token'))->first();
        if (!$user) {
            return $this->sendError('User not found', 401);
        }

        $this->orderRepository->where('driver_id', $user->id);
        $order = $this->orderRepository->findWithoutFail($id);

        if(empty($order)){
            return $this->sendError('Order not found', 401);
        }

        try{
            $order->delivery_date = date('Y-m-d');
            $order->order_status_id = 6;
            $order->save();
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }

        if($order && $order->user->device_token){
            try{
                sendNotification('Pedido entregue', 'Seu pedido foi entregue.', [$order->user->device_token]);
            }catch(\Exception $e){
                Log::error($e->getMessage());
            }
        }

        return $this->sendResponse($order->toArray(), 'Order delivered successfully');
    }

    public function markAsPaid(Request $request, $id){
        $user = $this->userRepository->findByField('api_token', $request->input('api_token'))->first();
        if (!$user) {
            return $this->sendError('User not found', 401);
        }

        $this->orderRepository->where('driver_id', $user->id);
        $order = $this->orderRepository->findWithoutFail($id);

        if(empty($order)){
            return $this->sendError('Order not found', 401);
        }

        try {
            if($order->payment->status != 'Pago'){
                $this->paymentRepository->markAsPaid($order);
            }
        } catch (\Exception $e) {
            Log::error($e->getMessage());
        }

        return $this->sendResponse($order->toArray(), 'Order paid successfully');
    }
}

resources/views/drivers/create.blade.php
@extends('layouts.app')
@push('css_lib')
  <!-- iCheck -->
  <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
  <!-- select2 -->
  <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
  <!-- bootstrap wysihtml5 - text editor -->
  <link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
  {{--dropzone--}}
  <link rel="stylesheet" href="{{asset('plugins/dropzone/bootstrap.min.css')}}">
@endpush
@section('content')
  <!-- Content Header (Page header) -->
  <div class="content-header">
    <div class="container-fluid">
      <div class="row mb-2">
        <div class="col-sm-6">
          <h1 class="m-0 text-dark">{{trans('lang.driver_plural')}} <small>{{trans('lang.driver_desc')}}</small></h1>
        </div><!-- /.col -->
        <div class="col-sm-6">
          <ol class="breadcrumb float-sm-right">
            <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
            <li class="breadcrumb-item"><a href="{!! route('drivers.index') !!}">{{trans('lang.driver_plural')}}</a>
            </li>
            <li class="breadcrumb-item active">{{trans('lang.driver_create')}}</li>
          </ol>
        </div><!-- /.col -->
      </div><!-- /.row -->
    </div><!-- /.container-fluid -->
  </div>

  <!-- /.content-header -->
  <div class="content">
    <div class="clearfix"></div>
    @include('flash::message')
    @include('adminlte-templates::common.errors')
    <div class="card">
      <div class="card-header">
        <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
          <li class="nav-item">
            <a class="nav-link" href="{!! route('drivers.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.driver_table')}}</a>
          </li>
          <li class="nav-item">
            <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.driver_create')}}</a>
          </li>
        </ul>
      </div>
      <div class="card-body">
        {!! Form::open(['route' => 'drivers.store']) !!}
        <div class="row">
          @include('drivers.fields')
        </div>
        {!! Form::close() !!}
        <div class="clearfix"></div>
      </div>
    </div>
    </div>
  </div>
  @include('layouts.media_modal',['collection'=>null])
@endsection
@push('scripts_lib')
  <!-- iCheck -->
  <script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
  <!-- select2 -->
  <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
  <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
  <script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
  {{--dropzone--}}
  <script src="{{asset('plugins/dropzone/dropzone.js')}}"></script>
  <script type="text/javascript">
    Dropzone.autoDiscover = false;
    var dropzoneFields = [];
  </script>
@endpush

resources/views/drivers/datatables_actions.blade.php
<div class='btn-group btn-group-sm'>
  {{--@can('drivers.show')
  <a data-toggle="tooltip" data-placement="bottom" title="{{trans('lang.view_details')}}" href="{{ route('drivers.show', $id) }}" class='btn btn-link'>
    <i class="fa fa-eye"></i>
  </a>
  @endcan--}}

  @can('drivers.edit')
  <a data-toggle="tooltip" data-placement="bottom" title="{{trans('lang.driver_edit')}}" href="{{ route('drivers.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  @endcan

  @can('drivers.destroy')
{!! Form::open(['route' => ['drivers.destroy', $id], 'method' => 'delete']) !!}
  {!! Form::button('<i class="fa fa-trash"></i>', [
  'type' => 'submit',
  'class' => 'btn btn-link text-danger',
  'onclick' => "return confirm('Você tem certeza?')"
  ]) !!}
{!! Form::close() !!}
  @endcan
</div>

resources/views/drivers/edit.blade.php
@extends('layouts.app')
@push('css_lib')
    <!-- iCheck -->
    <link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
    <!-- select2 -->
    <link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
    <!-- bootstrap wysihtml5 - text editor -->
    <link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
    {{--dropzone--}}
    <link rel="stylesheet" href="{{asset('plugins/dropzone/bootstrap.min.css')}}">
@endpush
@section('content')
    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')
        @include('adminlte-templates::common.errors')
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                    <li class="nav-item">
                        <a class="nav-link" href="{!! route('drivers.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.driver_table')}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{!! route('drivers.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.driver_create')}}</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-pencil mr-2"></i>{{trans('lang.driver_edit')}}</a>
                    </li>
                </ul>
            </div>
            <div class="card-body">
                {!! Form::model($user, ['route' => ['drivers.update', $user->id], 'method' => 'patch']) !!}
                <div class="row">
                    @include('drivers.fields')
                </div>
                {!! Form::close() !!}
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
    @include('layouts.media_modal',['collection'=>null])
@endsection

@push('scripts_lib')
    <!-- iCheck -->
    <script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
    <!-- select2 -->
    <script src="{{asset('plugins/select2/select2.min.js')}}"></script>
    <!-- AdminLTE dashboard demo (This is only for demo purposes) -->
    <script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
    {{--dropzone--}}
    <script src="{{asset('plugins/dropzone/dropzone.js')}}"></script>
    <script type="text/javascript">
        Dropzone.autoDiscover = false;
        var dropzoneFields = [];
    </script>
@endpush

resources/views/drivers/index.blade.php
@extends('layouts.app')

@section('content')
    <!-- Content Header (Page header) -->
    <div class="content-header">
        <div class="container-fluid">
            <div class="row mb-2">
                <div class="col-sm-6">
                    <h1 class="m-0 text-dark">{{trans('lang.driver_plural')}} <small>{{trans('lang.driver_desc')}}</small></h1>
                </div><!-- /.col -->
                <div class="col-sm-6">
                    <ol class="breadcrumb float-sm-right">
                        <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
                        <li class="breadcrumb-item"><a href="{!! route('drivers.index') !!}">{{trans('lang.driver_plural')}}</a>
                        </li>
                        <li class="breadcrumb-item active">{{trans('lang.driver_table')}}</li>
                    </ol>
                </div><!-- /.col -->
            </div><!-- /.row -->
        </div><!-- /.container-fluid -->
    </div>
    <!-- /.content-header -->

    <div class="content">
        <div class="clearfix"></div>
        @include('flash::message')
        <div class="card">
            <div class="card-header">
                <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
                    <li class="nav-item">
                        <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.driver_table')}}</a>
                    </li>
                    @can('drivers.create')
                        <li class="nav-item">
                            <a class="nav-link" href="{!! route('drivers.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.driver_create')}}</a>
                        </li>
                    @endcan
                    @include('layouts.right_toolbar', compact('dataTable'))
                </ul>
            </div>
            <div class="card-body">
                @include('drivers.table')
                <div class="clearfix"></div>
            </div>
        </div>
    </div>
@endsection

resources/views/drivers/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.driver_plural')}} <small>{{trans('lang.driver_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item active"><a href="{!! route('drivers.index') !!}">{{trans('lang.driver_plural')}}</a>
          </li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        <li class="nav-item">
          <a class="nav-link" href="{!! route('drivers.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.driver_table')}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{!! route('drivers.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.driver_create')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="row">
        @include('drivers.show_fields')

        <!-- Back Field -->
        <div class="form-group col-12 text-right">
          <a href="{!! route('drivers.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> {{trans('lang.back')}}</a>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@endsection

resources/views/drivers/show_fields.blade.php
<!-- Id Field -->
<div class="form-group row col-6">
  {!! Form::label('id', 'Id:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->id !!}</p>
  </div>
</div>

<!-- User Id Field -->
<div class="form-group row col-6">
  {!! Form::label('user_id', 'User Id:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->user_id !!}</p>
  </div>
</div>

<!-- Delivery Fee Field -->
<div class="form-group row col-6">
  {!! Form::label('delivery_fee', 'Delivery Fee:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->delivery_fee !!}</p>
  </div>
</div>

<!-- Total Orders Field -->
<div class="form-group row col-6">
  {!! Form::label('total_orders', 'Total Orders:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->total_orders !!}</p>
  </div>
</div>

<!-- Earning Field -->
<div class="form-group row col-6">
  {!! Form::label('earning', 'Earning:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->earning !!}</p>
  </div>
</div>

<!-- Available Field -->
<div class="form-group row col-6">
  {!! Form::label('available', 'Available:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->available !!}</p>
  </div>
</div>

<!-- Created At Field -->
<div class="form-group row col-6">
  {!! Form::label('created_at', 'Created At:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->created_at !!}</p>
  </div>
</div>

<!-- Updated At Field -->
<div class="form-group row col-6">
  {!! Form::label('updated_at', 'Updated At:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $driver->updated_at !!}</p>
  </div>
</div>

resources/views/drivers/table.blade.php
@push('css_lib')
@include('layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts_lib')
@include('layouts.datatables_js')
{!! $dataTable->scripts() !!}
@endpush