routes/web.php
            Route::get('uploads/all/{collection?}', 'UploadController@all');
            Route::get('uploads/collectionsNames', 'UploadController@collectionsNames');
            Route::post('uploads/clear', 'UploadController@clear')->name('medias.delete');
            Route::get('medias', 'UploadController@index')->name('medias');
            Route::get('uploads/clear-all', 'UploadController@clearAll');
        });

        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::get('permissions/role-has-permission', 'PermissionController@roleHasPermission');
            Route::get('permissions/refresh-permissions', 'PermissionController@refreshPermissions');
        });
        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::post('permissions/give-permission-to-role', 'PermissionController@givePermissionToRole');
            Route::post('permissions/revoke-permission-to-role', 'PermissionController@revokePermissionToRole');
        });

        Route::group(['middleware' => ['permission:app-settings']], function () {
            Route::prefix('settings')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::resource('roles', 'RoleController');
                Route::resource('customFields', 'CustomFieldController');
                Route::resource('currencies', 'CurrencyController')->except([
                    'show'
                ]);
                Route::get('users/login-as-user/{id}', 'UserController@loginAsUser')->name('users.login-as-user');
                Route::patch('update', 'AppSettingController@update');
                Route::patch('translate', 'AppSettingController@translate');
                Route::get('sync-translation', 'AppSettingController@syncTranslation');
                Route::get('clear-cache', 'AppSettingController@clearCache');
                Route::get('check-update', 'AppSettingController@checkForUpdates');
                // disable special character and number in route params
                Route::get('/{type?}/{tab?}', 'AppSettingController@index')
                    ->where('type', '[A-Za-z]*')->where('tab', '[A-Za-z]*')->name('app-settings');
            });
        });

        Route::post('fields/remove-media', 'FieldController@removeMedia');
        Route::resource('fields', 'FieldController')->except([
            'show'
        ]);

        Route::post('markets/remove-media', 'MarketController@removeMedia');
        Route::resource('markets', 'MarketController')->except([
            'show'
        ]);
        Route::get('markets/{id}/settings', 'MarketController@settings')->name('markets.settings');
        Route::post('markets/{id}/settings/weight_based_gtin', 'MarketController@weightBasedGtinPost')->name('markets.settings.weight_based_gtin.post');

        Route::resource('customers', 'CustomerController');

        Route::post('categories/remove-media', 'CategoryController@removeMedia');
        Route::resource('categories', 'CategoryController')->except([
            'show'
        ]);

        Route::resource('faqCategories', 'FaqCategoryController')->except([
            'show'
        ]);

        Route::resource('orderStatuses', 'OrderStatusController');

        Route::get('products/update_amounts', 'ProductController@updateAmounts');
        Route::post('products/update_amounts', 'ProductController@postUpdateAmounts');
        Route::get('products/import_from_database/{market_id}', 'ProductController@importFromDatabase')->name('products.import_from_database');
        Route::get('products/reload_from_server/{product_id}', 'ProductController@reloadFromServer')->name('products.reload_from_server');
        Route::post('products/import_from_database/{market_id}', 'ProductController@postImportFromDatabase')->name('products.import_from_database.post');
        Route::post('products/remove-media', 'ProductController@removeMedia');
        Route::resource('products', 'ProductController')->except([
            'show'
        ]);

        Route::post('galleries/remove-media', 'GalleryController@removeMedia');
        Route::resource('galleries', 'GalleryController')->except([
            'show'
        ]);

        Route::resource('productReviews', 'ProductReviewController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');


        Route::resource('payments', 'PaymentController')->except([
            'create',
            'store',
            'edit',
            'destroy'
        ]);
        ;

        Route::resource('faqs', 'FaqController')->except([
            'show'
        ]);
        Route::resource('marketReviews', 'MarketReviewController')->except([
            'show'
        ]);

        Route::resource('favorites', 'FavoriteController')->except([
            'show'
        ]);

        Route::get('orders/list/{type}', 'OrderController@list')->name('orders.list');
        Route::post('orders/{order_id}/add_product', 'OrderController@addProductOrder')->name('orders.add_product');
        Route::post('orders/{order_id}/remove_product/{product_id}', 'OrderController@removeProductOrder')->name('orders.remove_product');
        Route::post('orders/mark_as_sent', 'OrderController@markAsSent')->name('orders.mark_as_sent');
        Route::post('orders/mark_as_delivered', 'OrderController@markAsDelivered')->name('orders.mark_as_delivered');
        Route::get('orders/{order_id}/mark_as_delivered', 'OrderController@deliverOrder')->name('orders.deliver');
        Route::get('orders/{order_id}/mark_as_paid', 'OrderController@markAsPaid')->name('orders.mark_as_paid');
        Route::get('orders/{order_id}/change_status/{status}', 'OrderController@changeStatus')->name('orders.change_status');
        Route::get('orders/{order_id}/print_payment_receipt', 'OrderController@printPaymentReceipt')->name('orders.print_payment_receipt');
        Route::put('orders/{order_id}/restore', 'OrderController@restore')->name('orders.restore');
        Route::put('orders/{order_id}/update_quantities', 'OrderController@updateQuantities')->name('orders.update_quantities');
        Route::post('orders/{order_id}/add_new_product', 'OrderController@addProductOrder')->name('orders.add_new_product');
        Route::resource('orders', 'OrderController');

        Route::resource('notifications', 'NotificationController')->except([
            'create',
            'store',
            'update',
            'edit',
        ]);
        ;

        Route::resource('carts', 'CartController')->except([
            'show',
            'store',
            'create'
        ]);
        Route::resource('deliveryAddresses', 'DeliveryAddressController')->except([
            'show'
        ]);

        Route::get('drivers/reports', 'DriverController@reports')->name('drivers.reports');
        Route::post('drivers/remove-media', 'DriverController@removeMedia');
        Route::resource('drivers', 'DriverController');

        Route::get('order_pickers/reports', 'OrderPickerController@reports')->name('order_pickers.reports');
        Route::post('order_pickers/remove-media', 'OrderPickerController@removeMedia');
        Route::resource('order_pickers', 'OrderPickerController');

        Route::resource('earnings', 'EarningController')->except([
            'show',
            'edit',
            'update'
        ]);

        Route::resource('driversPayouts', 'DriversPayoutController')->except([
            'show',
            'edit',
            'update'
        ]);

        Route::resource('marketsPayouts', 'MarketsPayoutController')->except([
            'show',
            'edit',
            'update'
        ]);

        Route::resource('optionGroups', 'OptionGroupController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');

        Route::resource('options', 'OptionController')->except([
            'show'
        ]);

        Route::get('account', 'AccountController@index')->name('account.index');
        Route::get('account/add_market', 'AccountController@addMarket')->name('account.add_market');
        Route::post('account/add_market', 'AccountController@postAddMarket')->name('account.add_market.post');
        Route::get('account/monthly_payments', 'AccountController@monthlyPayments')->name('account.monthly_payments');
        Route::get('account/show_monthly_payment/{mp}', 'AccountController@showMonthlyPayment')->name('account.show_monthly_payment');
        Route::post('account/pay_monthly_payment/{mp}', 'AccountController@payMonthlyPayment')->name('account.pay_monthly_payment');



        Route::get('cash_register', 'CashRegisterController@index')->name('cash_register.index');
    });

    Route::get('login/{service}', 'Auth\LoginController@redirectToProvider');
    Route::get('login/{service}/callback', 'Auth\LoginController@handleProviderCallback');
    Auth::routes(['password.reset' => false]);

    Route::get('payments/failed', 'PayPalController@index')->name('payments.failed');
    Route::get('payments/razorpay/checkout', 'RazorPayController@checkout');
    Route::post('payments/razorpay/pay-success/{userId}/{deliveryAddressId?}', 'RazorPayController@paySuccess');
    Route::get('payments/razorpay', 'RazorPayController@index');

    Route::get('payments/paypal/express-checkout', 'PayPalController@getExpressCheckout')->name('paypal.express-checkout');
    Route::get('payments/paypal/express-checkout-success', 'PayPalController@getExpressCheckoutSuccess');
    Route::get('payments/paypal', 'PayPalController@index')->name('paypal.index');


app/Models/MarketsPayout.php
<?php
/**
 * File name: MarketsPayout.php
 * Last modified: 2020.04.30 at 06:29:44
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2020
 *
 */

namespace App\Models;

use Eloquent as Model;

/**
 * Class MarketsPayout
 * @package App\Models
 * @version March 25, 2020, 9:48 am UTC
 *
 * @property \App\Models\Market market
 * @property integer market_id
 * @property string method
 * @property double amount
 * @property dateTime paid_date
 * @property string note
 */
class MarketsPayout extends Model
{

    public $table = 'markets_payouts';
    


    public $fillable = [
        'market_id',
        'method',
        'amount',
        'paid_date',
        'note'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'market_id' => 'integer',
        'method' => 'string',
        'amount' => 'double',
        'paid_date' => 'datetime',
        'note' => 'string'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'market_id' => 'required|exists:markets,id',
        'method' => 'required',
        'note' => 'required',
        'amount' => 'required|min:0.01',
    ];

    /**
     * New Attributes
     *
     * @var array
     */
    protected $appends = [
        'custom_fields',
        
    ];

    public function customFieldsValues()
    {
        return $this->morphMany('App\Models\CustomFieldValue', 'customizable');
    }

    public function getCustomFieldsAttribute()
    {
        $hasCustomField = in_array(static::class,setting('custom_field_models',[]));
        if (!$hasCustomField){
            return [];
        }
        $array = $this->customFieldsValues()
            ->join('custom_fields','custom_fields.id','=','custom_field_values.custom_field_id')
            ->where('custom_fields.in_table','=',true)
            ->get()->toArray();

        return convertToAssoc($array,'name');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function market()
    {
        return $this->belongsTo(\App\Models\Market::class, 'market_id', 'id');
    }
    
}

resources/views/markets_payouts/create.blade.php
@extends('layouts.app')
@push('css_lib')
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
<!-- select2 -->
<link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
{{--dropzone--}}
<link rel="stylesheet" href="{{asset('plugins/dropzone/bootstrap.min.css')}}">
@endpush
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.markets_payout_plural')}} <small>{{trans('lang.markets_payout_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item"><a href="{!! route('marketsPayouts.index') !!}">{{trans('lang.markets_payout_plural')}}</a>
          </li>
          <li class="breadcrumb-item active">{{trans('lang.markets_payout_create')}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="clearfix"></div>
  @include('flash::message')
  @include('adminlte-templates::common.errors')
  <div class="clearfix"></div>
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        @can('marketsPayouts.index')
        <li class="nav-item">
          <a class="nav-link" href="{!! route('marketsPayouts.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.markets_payout_table')}}</a>
        </li>
        @endcan
        <li class="nav-item">
          <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.markets_payout_create')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      {!! Form::open(['route' => 'marketsPayouts.store']) !!}
      <div class="row">
        @include('markets_payouts.fields')
      </div>
      {!! Form::close() !!}
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@include('layouts.media_modal')
@endsection
@push('scripts_lib')
<!-- iCheck -->
<script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('plugins/select2/select2.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
{{--dropzone--}}
<script src="{{asset('plugins/dropzone/dropzone.js')}}"></script>
<script type="text/javascript">
    Dropzone.autoDiscover = false;
    var dropzoneFields = [];
</script>
@endpush

resources/views/markets_payouts/datatables_actions.blade.php
<div class='btn-group btn-group-sm'>
  @can('marketsPayouts.show')
  <a data-toggle="tooltip" data-placement="bottom" title="{{trans('lang.view_details')}}" href="{{ route('marketsPayouts.show', $id) }}" class='btn btn-link'>
    <i class="fa fa-eye"></i>
  </a>
  @endcan

  @can('marketsPayouts.edit')
  <a data-toggle="tooltip" data-placement="bottom" title="{{trans('lang.markets_payout_edit')}}" href="{{ route('marketsPayouts.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  @endcan

  @can('marketsPayouts.destroy')
{!! Form::open(['route' => ['marketsPayouts.destroy', $id], 'method' => 'delete']) !!}
  {!! Form::button('<i class="fa fa-trash"></i>', [
  'type' => 'submit',
  'class' => 'btn btn-link text-danger',
  'onclick' => "return confirm('Você tem certeza?')"
  ]) !!}
{!! Form::close() !!}
  @endcan
</div>

resources/views/markets_payouts/edit.blade.php
@extends('layouts.app')
@push('css_lib')
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
<!-- select2 -->
<link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
{{--dropzone--}}
<link rel="stylesheet" href="{{asset('plugins/dropzone/bootstrap.min.css')}}">
@endpush
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.markets_payout_plural')}} <small>{{trans('lang.markets_payout_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item"><a href="{!! route('marketsPayouts.index') !!}">{{trans('lang.markets_payout_plural')}}</a>
          </li>
          <li class="breadcrumb-item active">{{trans('lang.markets_payout_edit')}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="clearfix"></div>
  @include('flash::message')
  @include('adminlte-templates::common.errors')
  <div class="clearfix"></div>
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        @can('marketsPayouts.index')
        <li class="nav-item">
          <a class="nav-link" href="{!! route('marketsPayouts.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.markets_payout_table')}}</a>
        </li>
        @endcan
        @can('marketsPayouts.create')
        <li class="nav-item">
          <a class="nav-link" href="{!! route('marketsPayouts.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.markets_payout_create')}}</a>
        </li>
        @endcan
        <li class="nav-item">
          <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-pencil mr-2"></i>{{trans('lang.markets_payout_edit')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      {!! Form::model($marketsPayout, ['route' => ['marketsPayouts.update', $marketsPayout->id], 'method' => 'patch']) !!}
      <div class="row">
        @include('markets_payouts.fields')
      </div>
      {!! Form::close() !!}
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@include('layouts.media_modal')
@endsection
@push('scripts_lib')
<!-- iCheck -->
<script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('plugins/select2/select2.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
{{--dropzone--}}
<script src="{{asset('plugins/dropzone/dropzone.js')}}"></script>
<script type="text/javascript">
    Dropzone.autoDiscover = false;
    var dropzoneFields = [];
</script>
@endpush

resources/views/markets_payouts/fields.blade.php
@if($customFields)
<h5 class="col-12 pb-4">{!! trans('lang.main_fields') !!}</h5>
@endif
<div style="flex: 50%;max-width: 50%;padding: 0 4px;" class="column">
<!-- Market Id Field -->
<div class="form-group row ">
  {!! Form::label('market_id', trans("lang.markets_payout_market_id"),['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    {!! Form::select('market_id', $market, null, ['class' => 'select2 form-control']) !!}
    <div class="form-text text-muted">{{ trans("lang.markets_payout_market_id_help") }}</div>
  </div>
</div>


<!-- Method Field -->
<div class="form-group row ">
  {!! Form::label('method', trans("lang.markets_payout_method"),['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    {!! Form::select('method', ['Bank' => trans('lang.bank'),'Cash'=> trans('lang.cash')], null, ['class' => 'select2 form-control']) !!}
    <div class="form-text text-muted">{{ trans("lang.markets_payout_method_help") }}</div>
  </div>
</div>


<!-- Amount Field -->
<div class="form-group row ">
  {!! Form::label('amount', trans("lang.markets_payout_amount"), ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    {!! Form::number('amount', null,  ['class' => 'form-control','step'=>"any",'placeholder'=>  trans("lang.markets_payout_amount_placeholder")]) !!}
    <div class="form-text text-muted">
      {{ trans("lang.markets_payout_amount_help") }}
    </div>
  </div>
</div>
</div>
<div style="flex: 50%;max-width: 50%;padding: 0 4px;" class="column">

<!-- Note Field -->
<div class="form-group row ">
  {!! Form::label('note', trans("lang.markets_payout_note"), ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    {!! Form::textarea('note', null, ['class' => 'form-control','placeholder'=>
     trans("lang.markets_payout_note_placeholder")  ]) !!}
    <div class="form-text text-muted">{{ trans("lang.markets_payout_note_help") }}</div>
  </div>
</div>
</div>
@if($customFields)
<div class="clearfix"></div>
<div class="col-12 custom-field-container">
  <h5 class="col-12 pb-4">{!! trans('lang.custom_field_plural') !!}</h5>
  {!! $customFields !!}
</div>
@endif
<!-- Submit Field -->
<div class="form-group col-12 text-right">
  <button type="submit" class="btn btn-{{setting('theme_color')}}" ><i class="fa fa-save"></i> {{trans('lang.save')}} {{trans('lang.markets_payout')}}</button>
  <a href="{!! route('marketsPayouts.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> {{trans('lang.cancel')}}</a>
</div>

resources/views/markets_payouts/index.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.markets_payout_plural')}} <small>{{trans('lang.markets_payout_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item"><a href="{!! route('marketsPayouts.index') !!}">{{trans('lang.markets_payout_plural')}}</a>
          </li>
          <li class="breadcrumb-item active">{{trans('lang.markets_payout_table')}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->

<div class="content">
  <div class="clearfix"></div>
  @include('flash::message')
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        <li class="nav-item">
          <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.markets_payout_table')}}</a>
        </li>
        @can('marketsPayouts.create')
        <li class="nav-item">
          <a class="nav-link" href="{!! route('marketsPayouts.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.markets_payout_create')}}</a>
        </li>
        @endcan
        @include('layouts.right_toolbar', compact('dataTable'))
      </ul>
    </div>
    <div class="card-body">
      @include('markets_payouts.table')
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@endsection

resources/views/markets_payouts/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.markets_payout_plural')}} <small>{{trans('lang.markets_payout_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item active"><a href="{!! route('marketsPayouts.index') !!}">{{trans('lang.markets_payout_plural')}}</a>
          </li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        <li class="nav-item">
          <a class="nav-link" href="{!! route('marketsPayouts.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.markets_payout_table')}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{!! route('marketsPayouts.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.markets_payout_create')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="row">
        @include('markets_payouts.show_fields')

        <!-- Back Field -->
        <div class="form-group col-12 text-right">
          <a href="{!! route('marketsPayouts.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> {{trans('lang.back')}}</a>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@endsection

resources/views/markets_payouts/show_fields.blade.php
<!-- Id Field -->
<div class="form-group row col-6">
  {!! Form::label('id', 'Id:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->id !!}</p>
  </div>
</div>

<!-- Market Id Field -->
<div class="form-group row col-6">
  {!! Form::label('market_id', 'Market Id:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->market_id !!}</p>
  </div>
</div>

<!-- Method Field -->
<div class="form-group row col-6">
  {!! Form::label('method', 'Method:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->method !!}</p>
  </div>
</div>

<!-- Amount Field -->
<div class="form-group row col-6">
  {!! Form::label('amount', 'Amount:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->amount !!}</p>
  </div>
</div>

<!-- Paid Date Field -->
<div class="form-group row col-6">
  {!! Form::label('paid_date', 'Paid Date:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->paid_date !!}</p>
  </div>
</div>

<!-- Note Field -->
<div class="form-group row col-6">
  {!! Form::label('note', 'Note:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->note !!}</p>
  </div>
</div>

<!-- Created At Field -->
<div class="form-group row col-6">
  {!! Form::label('created_at', 'Created At:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->created_at !!}</p>
  </div>
</div>

<!-- Updated At Field -->
<div class="form-group row col-6">
  {!! Form::label('updated_at', 'Updated At:', ['class' => 'col-3 control-label text-right']) !!}
  <div class="col-9">
    <p>{!! $marketsPayout->updated_at !!}</p>
  </div>
</div>

resources/views/markets_payouts/table.blade.php
@push('css_lib')
@include('layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts_lib')
@include('layouts.datatables_js')
{!! $dataTable->scripts() !!}
@endpush