routes/web.php
<?php
/**
 * File name: web.php
 * Last modified: 2020.06.07 at 07:02:57
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2020
 *
 */

use Maatwebsite\Excel\Row;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/


Route::get('teste', 'AccountController@getMarketDbInfo');//Rota de teste para o codigo de importação

Route::get('', 'WebsiteController@index');
Route::get('login_register', 'WebsiteController@loginRegister');
Route::get('forgot_password', 'WebsiteController@forgotPassword');
Route::get('markets-list', 'WebsiteController@marketsList');
Route::get('change-market/{market?}', 'WebsiteController@changeMarket');
Route::get('market/{market}', 'WebsiteController@market');
Route::get('market/{market}/categories/{category}', 'WebsiteController@market');
Route::get('cart', 'WebsiteController@cart');
Route::get('checkout', 'WebsiteController@checkout');
Route::get('logout', 'WebsiteController@logout');
Route::get('fidelidade-remunerada', 'WebsiteController@fidelidadeRemunerada');
Route::get('password/reset/{token}', 'WebsiteController@passwordReset')->name('auth.password.reset');
Route::post('password/reset/{token}', 'WebsiteController@resetPassword');

Route::get('profile', 'WebsiteController@profile');
Route::get('favorites', 'WebsiteController@favorites');
Route::get('order/{order}', 'WebsiteController@order');

Route::post('save-localization', 'WebsiteController@saveLocalization');
Route::post('login', 'WebsiteController@login');
Route::post('update_user', 'WebsiteController@updateUser');
Route::post('register', 'WebsiteController@register');
Route::post('register_address', 'WebsiteController@register_address');
Route::post('update_address/{address_id}', 'WebsiteController@update_address');
Route::post('add_to_favorites', 'WebsiteController@addProductToFavorites');
Route::post('remove_from_favorites', 'WebsiteController@removeProductFromFavorites');
Route::post('add_product_to_cart', 'WebsiteController@addProductToCart');
Route::post('remove_product_from_cart', 'WebsiteController@removeProductFromCart');
Route::post('create_order', 'WebsiteController@createOrder');
Route::post('password_recovery', 'WebsiteController@sendPasswordRecoveryEmail');

Route::get('checkout/mercadopago/callback/{status}', 'WebsiteController@callback_mercadopago')->name('checkout_mercadopago_callback');
Route::get('checkout/mercadopago/{api_token}/{delivery_address_id}/{delivery_date?}', 'WebsiteController@mercadopago_app')->name('checkout_mercadopago_app');
Route::get('checkout/mercadopago_order/{api_token}/{order_id}', 'WebsiteController@mercadopago_app_order')->name('checkout_mercadopago_app_order');
Route::get('checkout/partial_payment_fr', 'API\FidelidadeRemunerada@partialPayment');
Route::post('checkout/partial_payment_fr', 'API\FidelidadeRemunerada@postPartialPayment');


Route::get('checkout/saldofr/{api_token}/{delivery_address_id}/{delivery_date?}', 'WebsiteController@saldofr_app')->name('checkout_saldofr_app');
Route::post('pay/saldofr/{api_token}/{delivery_address_id}/{delivery_date?}', 'WebsiteController@post_saldofr_app')->name('post_checkout_saldofr_app');

Route::get('storage/app/public/{id}/{conversion}/{filename?}', 'UploadController@storage');

Route::get('import_products', 'ImportsController@transformCsv');
Route::get('import_images_database_products', 'ImportsController@crawlImagesForDatabaseProducts');

Route::prefix('admin')->group(function () {
    Route::middleware('auth')->group(function () {
        Route::get('logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');
        Route::get('/', 'DashboardController@index')->name('dashboard');

        Route::post('uploads/store', 'UploadController@store')->name('medias.create');
        Route::get('users/profile', 'UserController@profile')->name('users.profile');
        Route::post('users/change_password', 'UserController@changePassword')->name('users.change_password');
        Route::post('users/remove-media', 'UserController@removeMedia');
        Route::resource('users', 'UserController');
        Route::get('dashboard', 'DashboardController@index')->name('dashboard');
        Route::get('dashboard/test', 'DashboardController@test')->name('dashboard.test');

        Route::group(['middleware' => ['permission:medias']], function () {
            Route::get('uploads/all/{collection?}', 'UploadController@all');
            Route::get('uploads/collectionsNames', 'UploadController@collectionsNames');
            Route::post('uploads/clear', 'UploadController@clear')->name('medias.delete');
            Route::get('medias', 'UploadController@index')->name('medias');
            Route::get('uploads/clear-all', 'UploadController@clearAll');
        });

        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::get('permissions/role-has-permission', 'PermissionController@roleHasPermission');
            Route::get('permissions/refresh-permissions', 'PermissionController@refreshPermissions');
        });
        Route::group(['middleware' => ['permission:permissions.index']], function () {
            Route::post('permissions/give-permission-to-role', 'PermissionController@givePermissionToRole');
            Route::post('permissions/revoke-permission-to-role', 'PermissionController@revokePermissionToRole');
        });

        Route::group(['middleware' => ['permission:app-settings']], function () {
            Route::prefix('settings')->group(function () {
                Route::resource('permissions', 'PermissionController');
                Route::resource('roles', 'RoleController');
                Route::resource('customFields', 'CustomFieldController');
                Route::resource('currencies', 'CurrencyController')->except([
                    'show'
                ]);
                Route::get('users/login-as-user/{id}', 'UserController@loginAsUser')->name('users.login-as-user');
                Route::patch('update', 'AppSettingController@update');
                Route::patch('translate', 'AppSettingController@translate');
                Route::get('sync-translation', 'AppSettingController@syncTranslation');
                Route::get('clear-cache', 'AppSettingController@clearCache');
                Route::get('check-update', 'AppSettingController@checkForUpdates');
                // disable special character and number in route params
                Route::get('/{type?}/{tab?}', 'AppSettingController@index')
                    ->where('type', '[A-Za-z]*')->where('tab', '[A-Za-z]*')->name('app-settings');
            });
        });

        Route::post('fields/remove-media', 'FieldController@removeMedia');
        Route::resource('fields', 'FieldController')->except([
            'show'
        ]);

        Route::post('markets/remove-media', 'MarketController@removeMedia');
        Route::resource('markets', 'MarketController')->except([
            'show'
        ]);
        Route::get('markets/{id}/settings', 'MarketController@settings')->name('markets.settings');
        Route::post('markets/{id}/settings/weight_based_gtin', 'MarketController@weightBasedGtinPost')->name('markets.settings.weight_based_gtin.post');

        Route::resource('customers', 'CustomerController');

        Route::post('categories/remove-media', 'CategoryController@removeMedia');
        Route::resource('categories', 'CategoryController')->except([
            'show'
        ]);

        Route::resource('faqCategories', 'FaqCategoryController')->except([
            'show'
        ]);

        Route::resource('orderStatuses', 'OrderStatusController');

        Route::get('products/update_amounts', 'ProductController@updateAmounts');
        Route::post('products/update_amounts', 'ProductController@postUpdateAmounts');
        Route::get('products/import_from_database/{market_id}', 'ProductController@importFromDatabase')->name('products.import_from_database');
        Route::get('products/reload_from_server/{product_id}', 'ProductController@reloadFromServer')->name('products.reload_from_server');
        Route::post('products/import_from_database/{market_id}', 'ProductController@postImportFromDatabase')->name('products.import_from_database.post');
        Route::post('products/remove-media', 'ProductController@removeMedia');
        Route::resource('products', 'ProductController')->except([
            'show'
        ]);

        Route::post('galleries/remove-media', 'GalleryController@removeMedia');
        Route::resource('galleries', 'GalleryController')->except([
            'show'
        ]);

        Route::resource('productReviews', 'ProductReviewController')->except([
            'show'
        ]);

        Route::post('options/remove-media', 'OptionController@removeMedia');


        Route::resource('payments', 'PaymentController')->except([
            'create',
            'store',
            'edit',
            'destroy'
        ]);
        ;

        Route::resource('faqs', 'FaqController')->except([
            'show'
        ]);
        Route::resource('marketReviews', 'MarketReviewController')->except([
            'show'
        ]);

        Route::resource('favorites', 'FavoriteController')->except([
            'show'
        ]);

        Route::get('orders/list/{type}', 'OrderController@list')->name('orders.list');
        Route::post('orders/{order_id}/add_product', 'OrderController@addProductOrder')->name('orders.add_product');

app/Models/Product.php
<?php
/**
 * File name: Product.php
 * Last modified: 2020.04.29 at 17:43:30
 * Author: SmarterVision - https://codecanyon.net/user/smartervision
 * Copyright (c) 2020
 *
 */

namespace App\Models;

use Eloquent as Model;
use Spatie\Image\Manipulations;
use Spatie\MediaLibrary\HasMedia\HasMedia;
use Spatie\MediaLibrary\HasMedia\HasMediaTrait;
use Spatie\MediaLibrary\Models\Media;

/**
 * Class Product
 * @package App\Models
 * @version August 29, 2019, 9:38 pm UTC
 *
 * @property \App\Models\Market market
 * @property \App\Models\Category category
 * @property \Illuminate\Database\Eloquent\Collection Option
 * @property \Illuminate\Database\Eloquent\Collection Nutrition
 * @property \Illuminate\Database\Eloquent\Collection ProductsReview
 * @property string name
 * @property double price
 * @property double discount_price
 * @property string description
 * @property double capacity
 * @property boolean featured
 * @property double package_items_count
 * @property string unit
 * @property integer market_id
 * @property integer category_id
 */
class Product extends Model implements HasMedia
{
    use HasMediaTrait {
        getFirstMediaUrl as protected getFirstMediaUrlTrait;
    }

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'name' => 'required',
        'price' => 'required|numeric|min:0',
        'market_id' => 'required|exists:markets,id',
        'category_id' => 'required|exists:categories,id'
    ];

    public $table = 'products';
    public $fillable = [
        'name',
        'ncm',
        'price',
        'discount_price',
        'description',
        'capacity',
        'package_items_count',
        'unit',
        'weight_based',
        'quantity_unit',
        'featured',
        'deliverable',
        'market_id',
        'category_id',
        'gtin_ean',
        'validated',
        'disabled',
        'manually_disabled',
    ];
    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'name' => 'string',
        'ncm' => 'string',
        'image' => 'string',
        'price' => 'double',
        'discount_price' => 'double',
        'description' => 'string',
        'capacity' => 'double',
        'package_items_count' => 'integer',
        'unit' => 'string',
        'weight_based' => 'integer',
        'quantity_unit' => 'string',
        'featured' => 'boolean',
        'deliverable' => 'boolean',
        'market_id' => 'integer',
        'category_id' => 'double',
        'gtin_ean' => 'string',
        'validated' => 'integer',
        'disabled' => 'integer',
        'manually_disabled' => 'integer'
    ];
    /**
     * New Attributes
     *
     * @var array
     */
    protected $appends = [
        'custom_fields',
        'has_media',
        'market'
    ];

    /**
     * @param Media|null $media
     * @throws \Spatie\Image\Exceptions\InvalidManipulation
     */
    public function registerMediaConversions(Media $media = null)
    {
        $this->addMediaConversion('thumb')
            ->fit(Manipulations::FIT_FILL, 500, 500)
            ->nonQueued();

        $this->addMediaConversion('icon')
            ->fit(Manipulations::FIT_FILL, 200, 200)
            ->nonQueued();
    }

    /**
     * to generate media url in case of fallback will
     * return the file type icon
     * @param string $conversion
     * @return string url
     */
    public function getFirstMediaUrl($collectionName = 'default', $conversion = '')
    {
        $url = $this->getFirstMediaUrlTrait($collectionName);
        $array = explode('.', $url);
        $extension = strtolower(end($array));
        if (in_array($extension, config('medialibrary.extensions_has_thumb'))) {
            return asset($this->getFirstMediaUrlTrait($collectionName, $conversion));
        } else {
            return asset(config('medialibrary.icons_folder') . '/' . $extension . '.png');
        }
    }

    public function getCustomFieldsAttribute()
    {
        $hasCustomField = in_array(static::class, setting('custom_field_models', []));
        if (!$hasCustomField) {
            return [];
        }
        $array = $this->customFieldsValues()
            ->join('custom_fields', 'custom_fields.id', '=', 'custom_field_values.custom_field_id')
            ->where('custom_fields.in_table', '=', true)
            ->get()->toArray();

        return convertToAssoc($array, 'name');
    }

    public function customFieldsValues()
    {
        return $this->morphMany('App\Models\CustomFieldValue', 'customizable');
    }

    /**
     * Add Media to api results
     * @return bool
     */
    public function getHasMediaAttribute()
    {
        return $this->hasMedia('image') ? true : false;
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function category()
    {
        return $this->belongsTo(\App\Models\Category::class, 'category_id', 'id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function options()
    {
        return $this->hasMany(\App\Models\Option::class, 'product_id');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsToMany
     **/
    public function optionGroups()
    {
        return $this->belongsToMany(\App\Models\OptionGroup::class,'options');
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\HasMany
     **/
    public function productReviews()
    {
        return $this->hasMany(\App\Models\ProductReview::class, 'product_id');
    }

    /**
     * get market attribute
     * @return \Illuminate\Database\Eloquent\Model|\Illuminate\Database\Eloquent\Relations\BelongsTo|object|null
     */
    public function getMarketAttribute()
    {
        return $this->market()->first(['id', 'fr_id', 'name', 'delivery_fee', 'free_delivery_above', 'address', 'phone', 'mercado_pago_token']);
    }

    /**
     * @return \Illuminate\Database\Eloquent\Relations\BelongsTo
     **/
    public function market()
    {
        return $this->belongsTo(\App\Models\Market::class, 'market_id', 'id');
    }


}

resources/views/products/create.blade.php
@extends('layouts.app')
@push('css_lib')
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
<!-- select2 -->
<link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
{{--dropzone--}}
<link rel="stylesheet" href="{{asset('plugins/dropzone/bootstrap.min.css')}}">
@endpush
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.product_plural')}} <small>{{trans('lang.product_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item"><a href="{!! route('products.index') !!}">{{trans('lang.product_plural')}}</a>
          </li>
          <li class="breadcrumb-item active">{{trans('lang.product_create')}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="clearfix"></div>
  @include('flash::message')
  @include('adminlte-templates::common.errors')
  <div class="clearfix"></div>
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        @can('products.index')
        <li class="nav-item">
          <a class="nav-link" href="{!! route('products.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.product_table')}}</a>
        </li>
        @endcan
        <li class="nav-item">
          <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.product_create')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      {!! Form::open(['route' => 'products.store']) !!}
      <div class="row">
        @include('products.fields')
      </div>
      {!! Form::close() !!}
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@include('layouts.media_modal')
@endsection
@push('scripts_lib')
<!-- iCheck -->
<script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('plugins/select2/select2.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
{{--dropzone--}}
<script src="{{asset('plugins/dropzone/dropzone.js')}}"></script>
<script type="text/javascript">
    Dropzone.autoDiscover = false;
    var dropzoneFields = [];
</script>
@endpush

resources/views/products/datatables_actions.blade.php
<div class='btn-group btn-group-sm'>
  @can('products.show')
  <a data-toggle="tooltip" data-placement="bottom" title="{{trans('lang.view_details')}}" href="{{ route('products.show', $id) }}" class='btn btn-link'>
    <i class="fa fa-eye"></i>
  </a>
  @endcan

  @can('products.edit')
  <a data-toggle="tooltip" data-placement="bottom" title="{{trans('lang.product_edit')}}" href="{{ (request()->validated && request()->validated == 'no') ? route('products.edit', [$id, 'validated' => 'no']) : route('products.edit', $id) }}" class='btn btn-link'>
    <i class="fa fa-edit"></i>
  </a>
  @endcan

  @can('products.destroy')
{!! Form::open(['route' => ['products.destroy', $id], 'method' => 'delete']) !!}
  {!! Form::button('<i class="fa fa-trash"></i>', [
  'type' => 'submit',
  'class' => 'btn btn-link text-danger',
  'onclick' => "return confirm('Você tem certeza?')"
  ]) !!}
{!! Form::close() !!}
  @endcan
</div>

resources/views/products/edit.blade.php
@extends('layouts.app')
@push('css_lib')
<!-- iCheck -->
<link rel="stylesheet" href="{{asset('plugins/iCheck/flat/blue.css')}}">
<!-- select2 -->
<link rel="stylesheet" href="{{asset('plugins/select2/select2.min.css')}}">
<!-- bootstrap wysihtml5 - text editor -->
<link rel="stylesheet" href="{{asset('plugins/summernote/summernote-bs4.css')}}">
{{--dropzone--}}
<link rel="stylesheet" href="{{asset('plugins/dropzone/bootstrap.min.css')}}">
@endpush
@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.product_plural')}} <small>{{trans('lang.product_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item"><a href="{!! route('products.index') !!}">{{trans('lang.product_plural')}}</a>
          </li>
          <li class="breadcrumb-item active">{{trans('lang.product_edit')}}</li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="clearfix"></div>
  @include('flash::message')
  @include('adminlte-templates::common.errors')
  <div class="clearfix"></div>
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        @can('products.index')
        <li class="nav-item">
          <a class="nav-link" href="{!! route('products.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.product_table')}}</a>
        </li>
        @endcan
        <li class="nav-item">
          <a class="nav-link active" href="{!! url()->current() !!}"><i class="fa fa-pencil mr-2"></i>{{trans('lang.product_edit')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div style="margin-bottom: 1rem;">
        Checar se imagem está disponivel em: <a href="<?php echo 'https://cdn-cosmos.bluesoft.com.br/products/'.$product->gtin_ean ?>" target="_blank"><?php echo 'https://cdn-cosmos.bluesoft.com.br/products/'.$product->gtin_ean ?></a>
      </div>
      {!! Form::model($product, ['route' => ['products.update', $product->id], 'method' => 'patch']) !!}
      @if(request()->validated && request()->validated == 'no')
        <input type="hidden" name="redirect_validated" value="1">
      @endif

      <div class="row">
        @include('products.fields')
      </div>
      {!! Form::close() !!}
      <div class="clearfix"></div>
    </div>
  </div>
</div>

<div class="modal fade" role="dialog" tabindex="-1" id="delete-product-modal">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      {!! Form::open(['route' => ['products.destroy', $product->id], 'method' => 'delete']) !!}
        <div class="modal-header">
          <h4 class="modal-title">Excluir produto</h4>
        </div>
        <div class="modal-body">
          <p>Você tem certeza que deseja excluir este produto?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
          <button class="btn btn-danger"><i class="fas fa-trash"></i> Excluir produto</button>
        </div>
      {!! Form::close() !!}
    </div>
  </div>
</div>
@include('layouts.media_modal')
@endsection
@push('scripts_lib')
<!-- iCheck -->
<script src="{{asset('plugins/iCheck/icheck.min.js')}}"></script>
<!-- select2 -->
<script src="{{asset('plugins/select2/select2.min.js')}}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{{asset('plugins/summernote/summernote-bs4.min.js')}}"></script>
{{--dropzone--}}
<script src="{{asset('plugins/dropzone/dropzone.js')}}"></script>
<script type="text/javascript">
    Dropzone.autoDiscover = false;
    var dropzoneFields = [];
</script>
@endpush

resources/views/products/show.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.product_plural')}} <small>{{trans('lang.product_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item active"><a href="{!! route('products.index') !!}">{{trans('lang.product_plural')}}</a>
          </li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        <li class="nav-item">
          <a class="nav-link" href="{!! route('products.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.product_table')}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{!! route('products.create') !!}"><i class="fa fa-plus mr-2"></i>{{trans('lang.product_create')}}</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <div class="row">
        @include('products.show_fields')

        <!-- Back Field -->
        <div class="form-group col-12 text-right">
          <a href="{!! route('products.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> {{trans('lang.back')}}</a>
        </div>
      </div>
      <div class="clearfix"></div>
    </div>
  </div>
</div>
@endsection

resources/views/products/table.blade.php
@push('css_lib')
@include('layouts.datatables_css')
@endpush

{!! $dataTable->table(['width' => '100%']) !!}

@push('scripts_lib')
@include('layouts.datatables_js')
{!! $dataTable->scripts() !!}
@endpush

resources/views/products/update_amounts.blade.php
@extends('layouts.app')

@section('content')
<!-- Content Header (Page header) -->
<div class="content-header">
  <div class="container-fluid">
    <div class="row mb-2">
      <div class="col-sm-6">
        <h1 class="m-0 text-dark">{{trans('lang.product_plural')}} <small>{{trans('lang.product_desc')}}</small></h1>
      </div><!-- /.col -->
      <div class="col-sm-6">
        <ol class="breadcrumb float-sm-right">
          <li class="breadcrumb-item"><a href="{{route('dashboard')}}"><i class="fa fa-dashboard"></i> {{trans('lang.dashboard')}}</a></li>
          <li class="breadcrumb-item active"><a href="{!! route('products.index') !!}">{{trans('lang.product_plural')}}</a>
          </li>
        </ol>
      </div><!-- /.col -->
    </div><!-- /.row -->
  </div><!-- /.container-fluid -->
</div>
<!-- /.content-header -->
<div class="content">
  <div class="card">
    <div class="card-header">
      <ul class="nav nav-tabs align-items-end card-header-tabs w-100">
        <li class="nav-item">
          <a class="nav-link" href="{!! route('products.index') !!}"><i class="fa fa-list mr-2"></i>{{trans('lang.product_table')}}</a>
        </li>
        <li class="nav-item">
          <a class="nav-link active" href="{!! route('products.create') !!}"><i class="fa fa-plus mr-2"></i>Atualizar valores de produtos</a>
        </li>
      </ul>
    </div>
    <div class="card-body">
      <form method="POST" action="/admin/products/update_amounts" enctype="multipart/form-data">
        @csrf
        <div class="row">
          <div class="col-12">
            @if(session('success'))
              <p class="text-success">{{ session('success') }}</p>
            @endif
            @if(session('error'))
              <p class="text-danger">{{ session('error') }}</p>
            @endif
          </div>

          <div class="form-group col-12">
            <label for="file">Selecione o arquivo de atualização dos valores</label><br>
            <small>Arquivo deve ser no formato .csv e conter as seguintes colunas: GTIN_EAN, NOME, PREÇO, o arquivo não deve ter um cabeçalho, a primeira linha já deve conter os dados dos produtos. Caso não exista um produto com o GTIN/EAN informado, um novo produto será criado.</small><br>
            <input type="file" name="file" id="file" class="form-control">
          </div>

          <!-- Back Field -->
          <div class="form-group col-12 text-right">
            <button type="submit" class="btn btn-primary mr-2"> Importar dados</button>
            <a href="{!! route('products.index') !!}" class="btn btn-default"><i class="fa fa-undo"></i> {{trans('lang.back')}}</a>
          </div>
        </div>
        <div class="clearfix"></div>
      </form>
    </div>
  </div>
</div>
@endsection